name: Test Secrets
on:
  push:
    branches: [ main ]

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    env:
      UNSECRET_SECRET: "This secret is not secret"

    steps:
      - name: Echo secrets
        uses: actions/checkout@v3

      - name: Echo env variable
        run: echo "UNSECRET_SECRET: ${{ UNSECRET_SECRET }}"

      - name: Echo github repo variable
        run: echo "MY_GITHUB_SECRET: ${{ secrets.MY_GITHUB_SECRET }}"

      - name: Echo github org variable
        run: echo "AZURE_API_SECRET: ${{ secrets.AZURE_API_SECRET }}"
