
name: "Hello World JS Action"

on:
  workflow_dispatch:
    inputs:
      input_one:
        description: "Who to greet"
        required: true
        default: "World"

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkput Repo
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Add actions/core and actions/github
        run: npm install @actions/core @actions/github --save-dev

      - name: Run JavaScript file
        id: set_output_time
        run: |
          echo "time=$(node index.js '${{ inputs.input_one }}')" >> $GITHUB_OUTPUT

      - name: Use the collected output value
        run: echo "The output value was ${{ steps.set_output_time.outputs.time }}"
